@startuml diagrama
entity UserPasswordOtp #ffc862 {
    Long id
    String requestId
    String otpHash
    Integer attempts
    boolean verified
    expirationTime expiresAt
    User user
}

entity PasswordResetToken #ffc862 {
    Long id
    String tokenHash
    LocalDateTime expiresAt
    boolean used
    User user
}

entity User #ffc862 {
    Long id
    String email
    String password
    String firstname
    String lastname
    Integer dni
    boolean active
    RoleName role
    List<Movement> movements
    List<DeliveryOrder> deliveryOrders
    List<DeliveryLine> deliveryLines
}

enum RoleName #ffc862 {
    ROLE_USER
    ROLE_OPERATOR
    ROLE_ADMIN
}

entity Company #ffaaaa {
    Long id
    String name
    List<StockLot> stockLots
}

entity StockLot #ffaaaa {
    Long id
    String batch
    Integer quantityReceived
    Integer quantityAvailable
    Integer quantityDelivered
    Integer quantityLost
    Integer quantityRecovered
    boolean zeroStock
    boolean temporary
    LocalDateTime createdAt
    LocalDateTime updatedAt
    Model model
    List<Movement> movements
    List<StockLot_DeliveryLine> stockLotDeliveryLines
    Company company
}

entity Model #d0ffb0{
    Long id
    String name
    String imageUrl
    String publicImageId
    LocalDate entryDate
    LocalDate caducityDate
    Integer totalQuantityAvailable
    Integer totalQuantityReceived
    Integer totalQuantityTaken
    Integer totalQuantityDelivered
    LocalDateTime createdAt
    LocalDateTime updatedAt
    boolean status
    Integer minimunAvailableQuantity
    boolean lowStock

    Product product
    List<Model_DeliveryOrder> modelDeliveryOrders
    List<Movement> movements
    List<DeliveryLine> deliveryLines
    List<StockLot> stockLots
}

entity Product #d0ffb0 {
    Long id
    String name
    BigDecimal length
    BigDecimal width
    BigDecimal height
    Integer quantityModels
    boolean status
    LocalDateTime updatedAt
    Category category
    Type type
    List<Model> models
}

entity Type #d0ffb0 {
    Long id
    String name
    boolean status
    List<Product> products
}

entity Category #d0ffb0 {
    Long id
    String name
    boolean status
    List<Product> products
}

entity Movement #fff891{
    Long id
    Integer quantity
    String comment
    LocalDateTime createdAt
    MovementType movementType
    User user
    StockLot stockLotReceiver
    StockLot stockLotEmitter
    DeliveryLine deliveryLine
    Model model
    List<Movement_StockLot> movement_StockLots
}

entity Movement_StockLot #fff891 {
    Long id
    Integer quantityTaken
    Movement movement
    StockLot stockLot
}

enum MovementType #fff891 {
    MOVEMENT_STOCK_RECEIVE
    MOVEMENT_STOCK_INCREASE
    MOVEMENT_STOCK_DECREASE
    MOVEMENT_STOCK_RECOVERY
    MOVEMENT_STOCK_TRANSFER
    MOVEMENT_STOCK_REFUND
    MOVEMENT_LINE_ALLOCATE
    MOVEMENT_LINE_ALTER
    MOVEMENT_LINE_RETURN
    MOVEMENT_LINE_CHANGE
    MOVEMENT_LINE_CANCELED
    MOVEMENT_LINE_LOST
    MOVEMENT_LINE_MISSING
    MOVEMENT_LINE_DELIVERED
    MOVEMENT_LINE_SIMULTANEOUS
}

entity DeliveryLine #ecbbff {
    Long id
    Integer originalQuantity
    Integer requiredQuantity
    Integer deliveredQuantity
    Integer pendingQuantity
    LocalDateTime limitDate
    LocalDateTime updatedAt
    LineStatus lineStatus
    Location location
    User userCreator
    User userUpdater
    List<StockLot_DeliveryLine> stockLotDeliveryLines
    List<Movement> movements
    Model model
    Model_DeliveryOrder model_DeliveryOrder
    DeliveryOrder deliveryOrder
}

entity StockLot_DeliveryLine #ecbbff{
    Long id
    Integer quantityUsed
    LocalDateTime createdAt
    StockLot stockLot
    DeliveryLine deliveryLine
}
enum LineStatus #ecbbff {
    LINE_MISSING
    LINE_READY
    LINE_PENDING
    LINE_DELIVERED
    LINE_CANCELED
    LINE_EXCEEDED
}

entity Location #bebebe{
    Long id
    String name
    String address
    boolean status
    Subregion subregion
    List<DeliveryLine> deliveryLines
}

entity Subregion #bebebe{
    Long id
    String name
    List<Location> locations
    Region region
}

entity Region #bebebe{
    Long id
    String name
    List<Subregion> subregions
}

entity Model_DeliveryOrder #89c6ff{
    Long id
    Integer requiredQuantityTotal
    boolean status
    DeliveryOrder deliveryOrder
    Model model
    List<DeliveryLine> deliveryLines
}

entity DeliveryOrder #89c6ff{
    Long id
    String batch
    LocalDateTime limitDate
    LocalDateTime priorityDate
    LocalDateTime createdAt
    LocalDateTime updatedAt
    OrderStatus orderStatus
    Double percentage
    LocalDateTime deliveredAt
    OnTimeStatus onTimeStatus
    User userCreator
    User userUpdater
    User userClient
    List<DeliveryLine> deliveryLines
    List<Model_DeliveryOrder> model_DeliveryOrders
}

enum OrderStatus #89c6ff {
    ORDER_READY
    ORDER_PENDING
    ORDER_DELIVERED
    ORDER_CANCELED
    ORDER_PARTIALLY_DELIVERED
}

enum OnTimeStatus #89c6ff {
    UNKNOWN
    ON_TIME
    LATE
}

RoleName ... User : requires
UserPasswordOtp *.. User : can have
PasswordResetToken *.. User : can have
Movement *... User : has
DeliveryOrder *.. User : assign
DeliveryOrder *.. User : creates
DeliveryOrder *.. User : update
DeliveryOrder ... OnTimeStatus : has delivered

DeliveryLine *... User : creates
DeliveryLine *... User : update

StockLot *.. Model : associates
StockLot .* Movement : receives
StockLot .* Movement : sends
StockLot .* StockLot_DeliveryLine : is present in
StockLot *. Company : send

Movement_StockLot *.. StockLot
Movement_StockLot *.. Movement

Category ..* Product : contains
Type ..* Product : contains
Model *. Product : has many

Model ..* Model_DeliveryOrder : is present in
Model ..* Movement : has
Model ..* DeliveryLine : has

StockLot_DeliveryLine *.. DeliveryLine: has many

Movement .. MovementType : type of
Movement *.. DeliveryLine : has

DeliveryLine *.. Model_DeliveryOrder : group
DeliveryLine *.. DeliveryOrder : has many
DeliveryLine .. LineStatus : type of
DeliveryLine *.. Location : assigned

Location *.. Subregion : has
Subregion *.. Region : has


Model_DeliveryOrder *.. DeliveryOrder : has many
DeliveryOrder .. OrderStatus : type of

@enduml
