@startuml diagrama
entity UserToken #ffc862 {
    Long id
    String token
    boolean active
    expirationTime LocalDateTime
    User user
}

entity User #ffc862 {
    Long id
    String email
    String password
    String firstname
    String lastname
    Integer dni
    boolean active
    List<Role> roles
    List<UserToken> userTokens
    List<Movement> movements
    List<DeliveryOrder> deliveryOrders
    List<DeliveryLine> deliveryLines
}

entity Role #ffc862 {
    Long id
    String name
    String label
}

entity Company #ffaaaa {
    Long id
    String name
    List<StockLot> stockLots
}

entity StockLot #ffaaaa {
    Long id
    String batch
    Integer quantityReceived
    Integer quantityAvailable
    Integer quantityDelivered
    Integer quantityLost
    Integer quantityRecovered
    boolean zeroStock
    boolean temporary
    LocalDateTime createdAt
    LocalDateTime updatedAt
    Model model
    List<Movement> movements
    List<StockLot_DeliveryLine> stockLotDeliveryLines
    Company company
}

entity Model #d0ffb0{
    Long id
    String name
    String imageUrl
    LocalDate entryDate
    LocalDate caducityDate
    Integer totalQuantityAvailable
    Integer totalQuantityReceived
    Integer totalQuantityDelivered
    LocalDateTime createdAt
    LocalDateTime updatedAt
    boolean status

    Product product
    List<Model_DeliveryOrder> modelDeliveryOrders
    List<Movement> movements
    List<DeliveryLine> deliveryLines
    List<StockLot> stockLots
}

entity Product #d0ffb0 {
    Long id
    String name
    BigDecimal length
    BigDecimal width
    BigDecimal height
    Integer quantityModels
    boolean status
    Category category
    Type type
    List<Model> models
}

entity Type #d0ffb0 {
    Long id
    String name
    List<Product> products
}

entity Category #d0ffb0 {
    Long id
    String name
    List<Product> products
}

entity Movement #fff891{
    Long id
    Integer quantity
    String comment
    LocalDateTime createdAt
    MovementType movementType
    User user
    StockLot stockLotReceiver
    StockLot stockLotEmitter
    DeliveryLine deliveryLine
    Model model
    List<Movement_StockLot> movement_StockLots
}

entity Movement_StockLot #fff891 {
    Long id
    Integer quantityTaken
    Movement movement
    StockLot stockLot
}

enum MovementType #fff891 {
    MOVEMENT_STOCK_RECEIVE
    MOVEMENT_STOCK_INCREASE
    MOVEMENT_STOCK_DECREASE
    MOVEMENT_STOCK_RECOVERY
    MOVEMENT_STOCK_TRANSFER
    MOVEMENT_LINE_ALLOCATE
    MOVEMENT_LINE_ALTER
    MOVEMENT_LINE_RETURN
    MOVEMENT_LINE_CHANGE
    MOVEMENT_LINE_CANCELED
    MOVEMENT_LINE_LOST
    MOVEMENT_LINE_MISSING
    MOVEMENT_LINE_DELIVERED
    MOVEMENT_LINE_SIMULTANEOUS
}

entity DeliveryLine #ecbbff {
    Long id
    Integer originalQuantity
    Integer requiredQuantity
    Integer deliveredQuantity
    Integer pendingQuantity
    LocalDateTime limitDate
    LocalDateTime updatedAt
    LineStatus lineStatus
    Location location
    User userCreator
    User userUpdater
    List<StockLot_DeliveryLine> stockLotDeliveryLines
    List<Movement> movements
    Model model
    Model_DeliveryOrder model_DeliveryOrder
    DeliveryOrder deliveryOrder
}

entity StockLot_DeliveryLine #ecbbff{
    Long id
    Integer quantityUsed
    LocalDateTime createdAt
    StockLot stockLot
    DeliveryLine deliveryLine
}
enum LineStatus #ecbbff {
    LINE_MISSING
    LINE_READY
    LINE_PENDING
    LINE_DELIVERED
    LINE_CANCELED
    LINE_EXCEEDED
}

entity Location #bebebe{
    Long id
    String name
    String address
    boolean status
    Subregion subregion
    List<DeliveryLine> deliveryLines
}

entity Subregion #bebebe{
    Long id
    String name
    List<Location> locations
    List<Model_DeliveryOrder_Subregion> model_DeliveryOrder_Subregions
}

entity Region #bebebe{
    Long id
    String name
    List<Subregion> subregions
    List<Model_DeliveryOrder_Region> model_DeliveryOrder_Regions
}

entity Model_DeliveryOrder #89c6ff{
    Long id
    Integer requiredQuantityTotal
    boolean status
    DeliveryOrder deliveryOrder
    Model model
    List<DeliveryLine> deliveryLines
    List<Model_DeliveryOrder_Region> model_DeliveryOrder_Regions
    List<Model_DeliveryOrder_Subregion> model_DeliveryOrder_Subregions
}

entity DeliveryOrder #89c6ff{
    Long id
    String batch
    LocalDateTime limitDate
    LocalDateTime priorityDate
    LocalDateTime createdAt
    LocalDateTime updatedAt
    OrderStatus orderStatus
    User userCreator
    User userUpdater
    User userClient
    List<DeliveryLine> deliveryLines
    List<Model_DeliveryOrder> model_DeliveryOrders
}

enum OrderStatus #89c6ff {
    ORDER_READY
    ORDER_PENDING
    ORDER_DELIVERED
    ORDER_CANCELED
}

entity Model_DeliveryOrder_Region #91fff9{
    Long id
    Integer requiredTotalQuantity
    LocalDateTime updatedAt
    Region region
    Model_DeliveryOrder model_DeliveryOrder
}

entity Model_DeliveryOrder_Subregion #91fff9{
  Long id
  Integer requiredTotalQuantity
  LocalDateTime updatedAt
  Subregion subregion
  Model_DeliveryOrder model_DeliveryOrder
}

Role *.* User : requires
UserToken *.. User : can have
Movement *... User : has
DeliveryOrder *.. User : assign
DeliveryOrder *.. User : creates
DeliveryOrder *.. User : update
DeliveryLine *... User : creates
DeliveryLine *... User : update

StockLot *.. Model : associates
StockLot .* Movement : receives
StockLot .* Movement : sends
StockLot .* StockLot_DeliveryLine : is present in
StockLot *. Company : send

Movement_StockLot *.. StockLot
Movement_StockLot *.. Movement

Category ..* Product : contains
Type ..* Product : contains
Model *. Product : has many

Model ..* Model_DeliveryOrder : is present in
Model ..* Movement : has
Model ..* DeliveryLine : has

StockLot_DeliveryLine *.. DeliveryLine: has many

Movement .. MovementType : type of
Movement *.. DeliveryLine : has

DeliveryLine *.. Model_DeliveryOrder : group
DeliveryLine *.. DeliveryOrder : has many
DeliveryLine .. LineStatus : type of
DeliveryLine *.. Location : assigned

Location *.. Subregion : has
Subregion *.. Region : has

Region ..* Model_DeliveryOrder_Region : group
Model_DeliveryOrder_Region *.. Model_DeliveryOrder : performs

Subregion ...* Model_DeliveryOrder_Subregion : group

Model_DeliveryOrder_Subregion *.. Model_DeliveryOrder : performs

Model_DeliveryOrder *.. DeliveryOrder : has many
DeliveryOrder .. OrderStatus : type of

@enduml
