DATASOURCE_URL = jdbc:mysql://localhost:3306/db_inventory_app_backend?useSSL=false&serverTimezone=GMT-5&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
DATASOURCE_USERNAME =root
DATASOURCE_PASSWORD =adminKing987#@
